//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHOOLMANAGEMENT
    {
        public int STUD_ID { get; set; }
        public string STUD_NAME { get; set; }
        public string CLASS { get; set; }
        public string SUBJECT { get; set; }
    }
}
